# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/xyh/NFS_Alinx/new-spi-demo/new-spi-demo.srcs/sources_1/ip/my_clk_generator/my_clk_generator.xci
# IP: The module: 'my_clk_generator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xyh/NFS_Alinx/new-spi-demo/new-spi-demo.srcs/sources_1/ip/my_clk_generator/my_clk_generator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_clk_generator'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/xyh/NFS_Alinx/new-spi-demo/new-spi-demo.srcs/sources_1/ip/my_clk_generator/my_clk_generator.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_clk_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/xyh/NFS_Alinx/new-spi-demo/new-spi-demo.srcs/sources_1/ip/my_clk_generator/my_clk_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_clk_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/xyh/NFS_Alinx/new-spi-demo/new-spi-demo.srcs/sources_1/ip/my_clk_generator/my_clk_generator.xci
# IP: The module: 'my_clk_generator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xyh/NFS_Alinx/new-spi-demo/new-spi-demo.srcs/sources_1/ip/my_clk_generator/my_clk_generator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_clk_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/xyh/NFS_Alinx/new-spi-demo/new-spi-demo.srcs/sources_1/ip/my_clk_generator/my_clk_generator.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_clk_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/xyh/NFS_Alinx/new-spi-demo/new-spi-demo.srcs/sources_1/ip/my_clk_generator/my_clk_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'my_clk_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
