set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]

set_property PACKAGE_PIN J14 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS18 [get_ports sys_clk]

set_property PACKAGE_PIN AB15 [get_ports adc1_clk_ref]
set_property IOSTANDARD LVCMOS25 [get_ports adc1_clk_ref]

set_property PACKAGE_PIN AC23 [get_ports adc2_clk_ref]
set_property IOSTANDARD LVCMOS25 [get_ports adc2_clk_ref]

set_property PACKAGE_PIN AA10 [get_ports {adc1_data_n[0]}]
set_property PACKAGE_PIN Y10 [get_ports {adc1_data_p[0]}]
set_property PACKAGE_PIN AF10 [get_ports {adc1_data_n[1]}]
set_property PACKAGE_PIN AE11 [get_ports {adc1_data_p[1]}]
set_property PACKAGE_PIN AD15 [get_ports {adc1_data_n[10]}]
set_property PACKAGE_PIN AD16 [get_ports {adc1_data_p[10]}]
set_property PACKAGE_PIN AF14 [get_ports {adc1_data_n[11]}]
set_property PACKAGE_PIN AF15 [get_ports {adc1_data_p[11]}]
set_property PACKAGE_PIN AD11 [get_ports {adc1_data_n[2]}]
set_property PACKAGE_PIN AC12 [get_ports {adc1_data_p[2]}]
set_property PACKAGE_PIN AD10 [get_ports {adc1_data_n[3]}]
set_property PACKAGE_PIN AE10 [get_ports {adc1_data_p[3]}]
set_property PACKAGE_PIN AC11 [get_ports {adc1_data_n[4]}]
set_property PACKAGE_PIN AB12 [get_ports {adc1_data_p[4]}]
set_property PACKAGE_PIN Y11 [get_ports {adc1_data_n[5]}]
set_property PACKAGE_PIN Y12 [get_ports {adc1_data_p[5]}]
set_property PACKAGE_PIN AB10 [get_ports {adc1_data_n[6]}]
set_property PACKAGE_PIN AB11 [get_ports {adc1_data_p[6]}]
set_property PACKAGE_PIN AF13 [get_ports {adc1_data_n[7]}]
set_property PACKAGE_PIN AE13 [get_ports {adc1_data_p[7]}]
set_property PACKAGE_PIN Y13 [get_ports {adc1_data_n[8]}]
set_property PACKAGE_PIN W13 [get_ports {adc1_data_p[8]}]
set_property PACKAGE_PIN AF12 [get_ports {adc1_data_n[9]}]
set_property PACKAGE_PIN AE12 [get_ports {adc1_data_p[9]}]
set_property PACKAGE_PIN AD14 [get_ports adc1_clk_n]
set_property PACKAGE_PIN AC14 [get_ports adc1_clk_p]
set_property PACKAGE_PIN AE16 [get_ports adc1_spi_ce]
set_property PACKAGE_PIN AB14 [get_ports adc1_spi_sclk]
set_property PACKAGE_PIN AE15 [get_ports adc1_spi_io]

set_property PACKAGE_PIN AF20 [get_ports {adc2_data_n[0]}]
set_property PACKAGE_PIN AF19 [get_ports {adc2_data_p[0]}]
set_property PACKAGE_PIN AE21 [get_ports {adc2_data_n[1]}]
set_property PACKAGE_PIN AE20 [get_ports {adc2_data_p[1]}]
set_property PACKAGE_PIN AE26 [get_ports {adc2_data_n[10]}]
set_property PACKAGE_PIN AE25 [get_ports {adc2_data_p[10]}]
set_property PACKAGE_PIN AD26 [get_ports {adc2_data_n[11]}]
set_property PACKAGE_PIN AD25 [get_ports {adc2_data_p[11]}]
set_property PACKAGE_PIN AC22 [get_ports {adc2_data_n[2]}]
set_property PACKAGE_PIN AC21 [get_ports {adc2_data_p[2]}]
set_property PACKAGE_PIN AD19 [get_ports {adc2_data_n[3]}]
set_property PACKAGE_PIN AD18 [get_ports {adc2_data_p[3]}]
set_property PACKAGE_PIN AB20 [get_ports {adc2_data_n[4]}]
set_property PACKAGE_PIN AA20 [get_ports {adc2_data_p[4]}]
set_property PACKAGE_PIN AF22 [get_ports {adc2_data_n[5]}]
set_property PACKAGE_PIN AE22 [get_ports {adc2_data_p[5]}]
set_property PACKAGE_PIN AB22 [get_ports {adc2_data_n[6]}]
set_property PACKAGE_PIN AB21 [get_ports {adc2_data_p[6]}]
set_property PACKAGE_PIN AF23 [get_ports {adc2_data_n[7]}]
set_property PACKAGE_PIN AE23 [get_ports {adc2_data_p[7]}]
set_property PACKAGE_PIN AF25 [get_ports {adc2_data_n[8]}]
set_property PACKAGE_PIN AF24 [get_ports {adc2_data_p[8]}]
set_property PACKAGE_PIN AA23 [get_ports {adc2_data_n[9]}]
set_property PACKAGE_PIN AA22 [get_ports {adc2_data_p[9]}]
set_property PACKAGE_PIN AD24 [get_ports adc2_clk_n]
set_property PACKAGE_PIN AD23 [get_ports adc2_clk_p]
set_property PACKAGE_PIN AC24 [get_ports adc2_spi_ce]
set_property PACKAGE_PIN AF18 [get_ports adc2_spi_sclk]
set_property PACKAGE_PIN AE18 [get_ports adc2_spi_io]

set_property IOSTANDARD LVCMOS25 [get_ports adc1_spi_ce]
set_property IOSTANDARD LVCMOS25 [get_ports adc1_spi_io]
set_property IOSTANDARD LVCMOS25 [get_ports adc1_spi_sclk]
set_property IOSTANDARD LVCMOS25 [get_ports adc2_spi_ce]
set_property IOSTANDARD LVCMOS25 [get_ports adc2_spi_io]
set_property IOSTANDARD LVCMOS25 [get_ports adc2_spi_sclk]


