# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/top.xdc

# XDC: new/gpio.xdc

# XDC: new/leds.xdc

# IP: ip/ILA_XYH/ILA_XYH.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ILA_XYH || ORIG_REF_NAME==ILA_XYH} -quiet] -quiet

# Block Designs: bd/CCD231/CCD231.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CCD231 || ORIG_REF_NAME==CCD231} -quiet] -quiet

# IP: bd/CCD231/ip/CCD231_processing_system7_0_1/CCD231_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CCD231_processing_system7_0_1 || ORIG_REF_NAME==CCD231_processing_system7_0_1} -quiet] -quiet

# IP: bd/CCD231/ip/CCD231_axi_interconnect_0_1/CCD231_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CCD231_axi_interconnect_0_1 || ORIG_REF_NAME==CCD231_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/CCD231/ip/CCD231_axi_gpio_0_1/CCD231_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CCD231_axi_gpio_0_1 || ORIG_REF_NAME==CCD231_axi_gpio_0_1} -quiet] -quiet

# IP: bd/CCD231/ip/CCD231_rst_ps7_0_148M_1/CCD231_rst_ps7_0_148M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CCD231_rst_ps7_0_148M_1 || ORIG_REF_NAME==CCD231_rst_ps7_0_148M_1} -quiet] -quiet

# IP: bd/CCD231/ip/CCD231_axi_gpio_0_0/CCD231_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CCD231_axi_gpio_0_0 || ORIG_REF_NAME==CCD231_axi_gpio_0_0} -quiet] -quiet

# IP: bd/CCD231/ip/CCD231_xbar_0/CCD231_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CCD231_xbar_0 || ORIG_REF_NAME==CCD231_xbar_0} -quiet] -quiet

# IP: bd/CCD231/ip/CCD231_auto_pc_0/CCD231_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CCD231_auto_pc_0 || ORIG_REF_NAME==CCD231_auto_pc_0} -quiet] -quiet

# XDC: bd/CCD231/CCD231_ooc.xdc
