# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param tcl.collectionResultDisplayLimit 0
create_project -in_memory -part xc7z035ffg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.cache/wt [current_project]
set_property parent.project_path /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/sources_1/src/adc_spi.v
  /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/sources_1/imports/rtl/aq_axi_master.v
  /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/sources_1/src/lut_config.v
  /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/sources_1/imports/rtl/mem_test.v
  /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/sources_1/src/spi_config.v
  /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/sources_1/src/spi_master.v
  /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/sources_1/bd/system/hdl/system_wrapper.v
  /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/sources_1/src/top.v
}
add_files /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/sources_1/bd/system/system_ooc.xdc]

read_ip -quiet /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/sources_1/ip/sys_pll/sys_pll.xci
set_property used_in_implementation false [get_files -all /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/sources_1/ip/sys_pll/sys_pll_board.xdc]
set_property used_in_implementation false [get_files -all /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/sources_1/ip/sys_pll/sys_pll.xdc]
set_property used_in_implementation false [get_files -all /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/sources_1/ip/sys_pll/sys_pll_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/constrs_1/new/fl9627_ax7350.xdc
set_property used_in_implementation false [get_files /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/constrs_1/new/fl9627_ax7350.xdc]

read_xdc /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/constrs_1/new/debug.xdc
set_property used_in_implementation false [get_files /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/constrs_1/new/debug.xdc]

read_xdc /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/constrs_1/imports/new/top.xdc
set_property used_in_implementation false [get_files /home/xyh/NFS_Alinx/adc_test_4ch/adc_test_4ch.srcs/constrs_1/imports/new/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xc7z035ffg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
